---
- name: Deploy Flask App in Docker
  hosts: webserver
  become: yes  # Run as sudo/root

  tasks:
    - name: Install required system packages
      yum:
        name:
          - python3
          - python3-pip  # Required for Flask app
        state: present
        update_cache: yes

    - name: Ensure boto3 is installed on EC2
      pip:
        name: boto3
        state: present
        executable: pip3

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create a directory for the Flask app
      file:
        path: /home/ec2-user/flask-app
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Copy Flask app files to the server
      copy:
        src: ../flask-app/
        dest: /home/ec2-user/flask-app/
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: Build Docker image
      command:
        cmd: docker build -t flask-app .
        chdir: /home/ec2-user/flask-app

    - name: Stop and remove existing container (if running)
      command: docker rm -f my-flask-app
      ignore_errors: yes

    - name: Run Flask app in a container
      command:
        cmd: docker run -d -p 80:80 --name my-flask-app flask-app
