name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.76.163.1 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          # Create a simple inventory file for SSH connection
          echo "[webserver]" > inventory.ini
          echo "54.76.163.1 ansible_user=ec2-user" >> inventory.ini
          
          # Install Ansible
          sudo apt update
          sudo apt install -y ansible
          
          # Run the Ansible playbook
          ansible-playbook -i inventory.ini flask-app/deploy_flask.yml -v
