name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Debug SSH Connection
        run: |
          echo "Testing SSH connection..."
          ssh -i /home/runner/.ssh/Security-key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.AWS_HOST }} "echo 'SSH Connection Successful'"

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i NetworkSec.ini flask-app/deploy_flask.yml

