name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ansible python3-pip
          
          # Install boto3 in system Python
          pip3 install boto3 botocore
          
          # Install AWS collections for Ansible
          ansible-galaxy collection install amazon.aws

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Create Ansible Config for AWS
        run: |
          echo "[defaults]" > ansible.cfg
          echo "host_key_checking = False" >> ansible.cfg
          
          # Create updated inventory file
          echo "[webserver]" > NetworkSec.ini
          echo "54.76.163.1 ansible_connection=aws_ssm ansible_aws_ssm_region=${{ secrets.AWS_REGION }} ansible_user=ec2-user ansible_python_interpreter=/usr/bin/python3" >> NetworkSec.ini
          
          # Display created files for debugging
          echo "Created ansible.cfg:"
          cat ansible.cfg
          echo "Created NetworkSec.ini:"
          cat NetworkSec.ini

      - name: Run Ansible Playbook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          ansible-playbook -i NetworkSec.ini flask-app/deploy_flask.yml -v
