name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y ansible unzip python3-pip

          # Find Ansible's Python path
          ANSIBLE_PYTHON_PATH=$(ansible --version | grep "python version" | awk '{print $4}')
          echo "Ansible is using Python at: $ANSIBLE_PYTHON_PATH"
          
          # Get the directory of Ansible's Python
          ANSIBLE_PYTHON_DIR=$(dirname $ANSIBLE_PYTHON_PATH)
          echo "Ansible Python directory: $ANSIBLE_PYTHON_DIR"
          
          # Install boto3 using Ansible's pip
          sudo $ANSIBLE_PYTHON_DIR/pip install boto3 botocore
          
          # Also install in the system Python for good measure
          pip3 install boto3 botocore

          # Check AWS CLI installation & update if needed
          if aws --version > /dev/null 2>&1; then
            echo "AWS CLI already installed. Updating..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update
          else
            echo "AWS CLI not found. Installing..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi

          aws --version  # Verify installation

      - name: Configure AWS CLI with Static Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      - name: Verify AWS SSM Access
        run: aws ssm describe-instance-information

      - name: Run Ansible Playbook using AWS SSM
        run: |
          ansible-playbook -i NetworkSec.ini flask-app/deploy_flask.yml --extra-vars "ansible_python_interpreter=/usr/bin/python3"
