name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Ansible & AWS CLI
        run: |
          sudo apt update
          sudo apt install -y ansible unzip
          if aws --version > /dev/null 2>&1; then
            echo "AWS CLI already installed. Updating..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update
          else
            echo "AWS CLI not found. Installing..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi
          aws --version

      - name: Debug AWS Secrets
        run: |
          echo "AWS Account ID: ${{ secrets.AWS_ACCOUNT_ID }}"
          echo "Role ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::156507000928:role/GitHubActionsRole #arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          role-session-name: GitHubActionsSession
          aws-region: eu-west-1

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      - name: Verify AWS SSM Access
        run: aws ssm describe-instance-information

      - name: Run Ansible Playbook using AWS SSM
        run: ansible-playbook -i NetworkSec.ini flask-app/deploy_flask.yml
