name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Ansible & AWS CLI
        run: |
          sudo apt update
          sudo apt install -y ansible awscli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsRole
          role-session-name: GitHubActionsSession
          aws-region: eu-west-1  # Change to your AWS region

      - name: Verify AWS SSM Access
        run: aws ssm describe-instance-information

      - name: Run Ansible Playbook using AWS SSM
        run: |
          ansible-playbook -i NetworkSec.ini flask-app/deploy_flask.yml
